In [3]:
import torch
import numpy as np

In [4]:
data = [[1, 2], [3, 4]]
data_tensor = torch.tensor(data)
print(data_tensor, type(data_tensor))

tensor([[ 1,  2],
        [ 3,  4]]) <class 'torch.Tensor'>


In [5]:
data = [[1, 2], [3, 4], [5, 6]]
np_data = np.array(data)
print(np_data, type(np_data))
np_data_tensor = torch.from_numpy(np_data)
print(np_data_tensor, type(np_data_tensor))

[[1 2]
 [3 4]
 [5 6]] <class 'numpy.ndarray'>
tensor([[ 1,  2],
        [ 3,  4],
        [ 5,  6]]) <class 'torch.Tensor'>


In [6]:
torch.zeros(5)

tensor([ 0.,  0.,  0.,  0.,  0.])

In [7]:
torch.ones(2, 2)

tensor([[ 1.,  1.],
        [ 1.,  1.]])

In [8]:
torch.rand(3, 3, 3)

tensor([[[ 0.7589,  0.8828,  0.9603],
         [ 0.9907,  0.9283,  0.0082],
         [ 0.7712,  0.2500,  0.1694]],

        [[ 0.8382,  0.6372,  0.7153],
         [ 0.4291,  0.0689,  0.1261],
         [ 0.9102,  0.1306,  0.2511]],

        [[ 0.6717,  0.9957,  0.9753],
         [ 0.6735,  0.2204,  0.5911],
         [ 0.9991,  0.7387,  0.6544]]])

In [9]:
zero_tensor = torch.zeros(3, 3)
ones_like_zeros = torch.ones_like(zero_tensor)

print(zero_tensor.shape, ones_like_zeros.shape)

torch.Size([3, 3]) torch.Size([3, 3])


In [10]:
zero_tensor[0]

tensor([ 0.,  0.,  0.])

In [11]:
ones_like_zeros[:, 0]

tensor([ 1.,  1.,  1.])

In [12]:
x = ones_like_zeros.detach()
print(x)

tensor([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  1.,  1.]])


In [13]:
x[:, 0] * 5

tensor([ 5.,  5.,  5.])

In [14]:
rand1 = torch.rand(5)
rand2 = torch.rand(5)
torch.matmul(rand1, rand2)

tensor(0.5864)

In [15]:
rand1 = torch.rand(5, 5)
rand2 = torch.rand(5, 5)
torch.matmul(rand1, rand2)

tensor([[ 0.4367,  2.0719,  0.8827,  0.9421,  1.2820],
        [ 0.2053,  0.8358,  0.2140,  0.4557,  1.1095],
        [ 0.3849,  1.9726,  0.8018,  0.8197,  1.6638],
        [ 0.3802,  2.1434,  0.9840,  1.0614,  1.4102],
        [ 0.2483,  1.3066,  0.7303,  0.8276,  1.1355]])